Repository ethui/ethui, pull requests merged in 2023-11, with the labels that each got.

#477 Prevent forge watcher from crashing with invalid directories
  crates/forge/src/manager.rs
  crates/forge/src/watcher.rs
  crates/ws/src/server.rs
Labels: bugfix

#479 Better 'from' detection when submitting transactionss
  crates/rpc/src/error.rs
  crates/rpc/src/lib.rs
  crates/rpc/src/send_transaction.rs
  crates/wallets/src/lib.rs
  crates/wallets/src/wallet.rs
  gui/src/components/ABIForm.tsx
Labels: bugfix

#484 Using alloy_primitives (Address)
  Cargo.lock
  Cargo.toml
  crates/broadcast/src/lib.rs
  crates/db/src/commands.rs
  crates/db/src/lib.rs
  crates/db/src/queries.rs
  crates/db/src/utils.rs
  crates/exchange-rates/src/feed.rs
  crates/forge/src/commands.rs
  crates/http/src/routes/settings.rs
  crates/http/src/routes/wallets.rs
  crates/rpc/src/error.rs
  crates/rpc/src/send_transaction.rs
  crates/settings/src/commands.rs
  crates/settings/src/lib.rs
  crates/simulator/Cargo.toml
  crates/simulator/src/evm.rs
  crates/simulator/src/types.rs
  crates/simulator/tests/detris.rs
  crates/sync/alchemy/src/lib.rs
  crates/sync/alchemy/src/types.rs
  crates/sync/alchemy/src/utils.rs
  crates/sync/anvil/Cargo.toml
  crates/sync/anvil/src/expanders.rs
  crates/sync/anvil/src/tracker.rs
  crates/sync/anvil/src/utils.rs
  crates/sync/src/commands.rs
  crates/sync/src/lib.rs
  crates/types/Cargo.toml
  crates/types/src/checksummed_address.rs
  crates/types/src/events.rs
  crates/types/src/lib.rs
  crates/types/src/tokens.rs
  crates/wallets/src/commands.rs
  crates/wallets/src/hd_wallet.rs
  crates/wallets/src/impersonator.rs
  crates/wallets/src/json_keystore_wallet.rs
  crates/wallets/src/lib.rs
  crates/wallets/src/plaintext.rs
  crates/wallets/src/utils.rs
  crates/wallets/src/wallet.rs
  crates/ws/src/peers.rs
  gui/src/components/AddressView.tsx
Labels: refactor

#485 Alloy: integer / bytes types
  crates/db/src/commands.rs
  crates/db/src/lib.rs
  crates/db/src/queries.rs
  crates/forge/src/abi.rs
  crates/forge/src/manager.rs
  crates/simulator/tests/detris.rs
  crates/sync/alchemy/src/error.rs
  crates/sync/alchemy/src/lib.rs
  crates/sync/alchemy/src/types.rs
  crates/sync/alchemy/src/utils.rs
  crates/sync/anvil/src/error.rs
  crates/sync/anvil/src/expanders.rs
  crates/sync/anvil/src/tracker.rs
  crates/sync/anvil/src/utils.rs
  crates/types/src/events.rs
  crates/types/src/lib.rs
  crates/types/src/tokens.rs
Labels: refactor

#494 Wallets form refactor
  gui/src/components/Settings/Network.tsx
  gui/src/components/Settings/Wallet/HDWallet.tsx
  gui/src/components/Settings/Wallet/Impersonator.tsx
  gui/src/components/Settings/Wallet/JsonKeystore.tsx
  gui/src/components/Settings/Wallet/Plaintext.tsx
  gui/src/components/Settings/Wallets.tsx
  gui/src/store/settings.ts
  gui/src/store/theme.ts
  gui/src/types.ts
  gui/src/types/index.ts
  gui/src/types/network.ts
  gui/src/types/password.ts
  gui/src/types/settings.ts
  gui/src/types/wallets.ts
Labels: refactor

#495 Refactors signing logic (to accomodate ledgers)
  Cargo.lock
  Cargo.toml
  crates/forge/src/abi.rs
  crates/rpc/src/error.rs
  crates/rpc/src/send_transaction.rs
  crates/rpc/src/sign_message.rs
  crates/sync/anvil/src/expanders.rs
  crates/types/src/lib.rs
  crates/wallets/src/commands.rs
  crates/wallets/src/error.rs
  crates/wallets/src/lib.rs
  crates/wallets/src/signer.rs
  crates/wallets/src/wallet.rs
  crates/wallets/src/wallets/hd_wallet.rs
  crates/wallets/src/wallets/impersonator.rs
  crates/wallets/src/wallets/json_keystore_wallet.rs
  crates/wallets/src/wallets/mod.rs
  crates/wallets/src/wallets/plaintext.rs
  crates/ws/src/peers.rs
Labels: refactor

#496 USB Ledger support
  Cargo.lock
  Cargo.toml
  bin/iron/src/app.rs
  crates/dialogs/src/handle.rs
  crates/rpc/src/error.rs
  crates/rpc/src/send_transaction.rs
  crates/wallets/Cargo.toml
  crates/wallets/src/commands.rs
  crates/wallets/src/error.rs
  crates/wallets/src/lib.rs
  crates/wallets/src/signer.rs
  crates/wallets/src/utils.rs
  crates/wallets/src/wallet.rs
  crates/wallets/src/wallets/hd_wallet.rs
  crates/wallets/src/wallets/impersonator.rs
  crates/wallets/src/wallets/json_keystore_wallet.rs
  crates/wallets/src/wallets/ledger.rs
  crates/wallets/src/wallets/mod.rs
  crates/wallets/src/wallets/plaintext.rs
  gui/src/components/Dialogs/TxReview.tsx
  gui/src/components/Settings/Wallet/HDWallet.tsx
  gui/src/components/Settings/Wallet/Ledger.tsx
  gui/src/components/Settings/Wallets.tsx
  gui/src/hooks/index.ts
  gui/src/hooks/useLedgerDetect.ts
  gui/src/types/wallets.ts
Labels: feature

#497 Dialog refactor
  bin/iron/src/app.rs
  crates/dialogs/src/commands.rs
  crates/dialogs/src/error.rs
  crates/dialogs/src/global.rs
  crates/dialogs/src/handle.rs
  crates/dialogs/src/lib.rs
  crates/rpc/src/send_transaction.rs
  crates/rpc/src/sign_message.rs
  crates/wallets/src/wallets/hd_wallet.rs
  crates/wallets/src/wallets/json_keystore_wallet.rs
  gui/src/components/Dialogs/MsgSign.tsx
  gui/src/hooks/useDialog.ts
Labels: refactor

#486 Devtool page in browser
  Justfile
  extension/package.json
  extension/src/background/index.ts
  extension/src/devtools/index.html
  extension/src/devtools/index.ts
  extension/src/panel/index.html
  extension/src/panel/index.tsx
  extension/src/panel/store.ts
  extension/src/public/manifest-chrome.json
  extension/src/public/manifest-firefox.json
  extension/src/types.ts
  extension/vite/base.ts
  package.json
  yarn.lock
Labels: feature

#509 Ensure at most 1 iron instance is running
  Cargo.lock
  bin/iron/Cargo.toml
  bin/iron/src/app.rs
  bin/iron/src/error.rs
  bin/iron/src/main.rs
  bin/iron/src/system_tray.rs
  bin/iron/src/utils.rs
  crates/broadcast/src/lib.rs
  crates/http/Cargo.toml
  crates/http/src/error.rs
  crates/http/src/init.rs
  crates/http/src/lib.rs
  crates/http/src/routes/mod.rs
  crates/http/src/routes/ui.rs
  crates/http/src/utils.rs
  crates/ws/src/server.rs
Labels: feature

#511 Statically linking libusb on macos
  .github/workflows/release.yml
  bin/iron/build.rs
Labels: bugfix

#512 Handling dialog window close events
  bin/iron/src/app.rs
  bin/iron/src/dialogs.rs
  bin/iron/src/main.rs
  crates/dialogs/src/error.rs
  crates/dialogs/src/handle.rs
  crates/dialogs/src/lib.rs
  crates/dialogs/src/utils.rs
  crates/rpc/src/send_transaction.rs
  crates/rpc/src/sign_message.rs
  crates/types/src/ui_events.rs
  crates/wallets/src/wallets/hd_wallet.rs
  crates/wallets/src/wallets/json_keystore_wallet.rs
Labels: bugfix

#513 Building extension after app
  .github/workflows/release.yml
Labels: chore

#515 Adding command-line arguments
  Cargo.lock
  Cargo.toml
  bin/iron/Cargo.toml
  bin/iron/src/app.rs
  bin/iron/src/main.rs
  crates/args/Cargo.toml
  crates/args/src/lib.rs
  crates/http/Cargo.toml
  crates/http/src/init.rs
  crates/http/src/utils.rs
  crates/ws/Cargo.toml
  crates/ws/src/init.rs
  crates/ws/src/server.rs
  gui/src/hooks/useApi.ts
Labels: feature

#516 Better RPC errors handling
  bin/iron/src/app.rs
  crates/http/src/lib.rs
  crates/http/src/routes/rpc.rs
  crates/rpc/src/error.rs
  crates/rpc/src/lib.rs
  crates/wallets/src/wallet.rs
  crates/ws/src/server.rs
Labels: enhancement

#517 Ability to start the app with --hidden
  Justfile
  bin/iron/src/app.rs
  bin/iron/src/system_tray.rs
  bin/iron/src/utils.rs
  crates/args/src/lib.rs
Labels: feature

#519 Autostart on boot
  Cargo.lock
  bin/iron/Cargo.toml
  bin/iron/src/app.rs
  bin/iron/src/error.rs
  bin/iron/src/utils.rs
  crates/settings/Cargo.toml
  crates/settings/src/autostart.rs
  crates/settings/src/error.rs
  crates/settings/src/init.rs
  crates/settings/src/lib.rs
  gui/src/components/Settings/General.tsx
  gui/src/types/settings.ts
Labels: feature

#522 Debug logs for extension
  extension/src/background/index.ts
Labels: chore

#523 Using version number from github release instead of package.json
  .github/workflows/release.yml
  extension/package.json
  extension/scripts/build.sh
Labels: chore

#526 Using yarn 4
  .eslintrc.js
  .github/workflows/extension.yml
  .gitignore
  .tool-versions
  .yarn/releases/yarn-4.0.2.cjs
  .yarnrc.yml
  crates/settings/src/autostart.rs
  crates/ws/src/init.rs
  extension/package.json
  extension/src/background/index.ts
  extension/src/content-script/index.ts
  extension/src/devtools/index.ts
  extension/src/inpage/index.ts
  extension/src/inpage/provider.ts
  extension/src/options/index.ts
  extension/src/panel/index.tsx
  extension/src/panel/store.ts
  extension/src/settings.ts
  gui/package.json
  gui/src/components/CommandBar.tsx
  gui/src/components/Connections.tsx
  gui/src/components/HomePage.tsx
  gui/src/components/Txs.tsx
  gui/src/hooks/tauri.ts
  gui/src/hooks/useHashLocation.ts
  gui/src/main.tsx
  gui/src/types/password.ts
  package.json
  yarn.lock
Labels: chore

#528 Fixing dev environment
  package.json
  yarn.lock
Labels: bugfix

#530 Yarn upgrade-interactive
  Cargo.lock
  crates/crypto/Cargo.toml
  extension/package.json
  gui/package.json
  package.json
  yarn.lock
Labels: chore

#531 Updating ethers
  Cargo.lock
  Cargo.toml
  crates/simulator/Cargo.toml
  crates/simulator/src/evm.rs
  crates/simulator/src/types.rs
  crates/types/Cargo.toml
  crates/types/src/lib.rs
Labels: chore

#532 Updating coins-ledger
  Cargo.lock
  Cargo.toml
  crates/wallets/Cargo.toml
Labels: chore

#533 Fully migrate iron_simulator to alloy
  Cargo.lock
  crates/rpc/Cargo.toml
  crates/rpc/src/send_transaction.rs
  crates/simulator/Cargo.toml
  crates/simulator/src/errors.rs
  crates/simulator/src/evm.rs
  crates/simulator/src/types.rs
Labels: refactor

#537 Fixing tauri-apps/tauri-action uploads
  Cargo.toml
Labels: bugfix

#539 Clearing release assets before re-running the workflow
  .github/workflows/release.yml
Labels: chore

#541 removes actions-rs/toolchain
  .github/workflows/release.yml
  .github/workflows/rust.yml
  .github/workflows/yarn.yml
Labels: chore

#542 Ledger retry
  Cargo.lock
  Cargo.toml
  crates/rpc/src/error.rs
  crates/rpc/src/send_transaction.rs
Labels: bugfix

#543 extension: close runtime port on tab unload
  extension/src/background/index.ts
  extension/src/content-script/index.ts
Labels: enhancement

#544 ws: less unwraps, more stability
  crates/rpc/src/error.rs
  crates/rpc/src/send_transaction.rs
  crates/ws/src/server.rs
Labels: enhancement
