Repository ethui/ethui, pull requests merged in 2023-08, with the labels that each got.

#335 Removing unused scripting permissions
  extension/src/public/manifest.json
  extension/src/public/manifestv2.json
Labels: bugfix

#342 Fixing yarn setup: extension build cmd
  package.json
Labels: bugfix

#343 Fixing account copy-to-clipboard button
  gui/src/components/Account.tsx
  gui/src/components/AddressView.tsx
Labels: bugfix

#341 Simplifying extension's code
  extension/package.json
  extension/src/background/index.ts
  extension/src/content-script/providerForward.ts
  extension/src/inpage/index.ts
  extension/src/inpage/provider.ts
  extension/src/inpage/provider/BaseProvider.ts
  extension/src/inpage/provider/IronInpageProvider.ts
  extension/src/inpage/provider/StreamProvider.ts
  extension/src/inpage/provider/index.ts
  extension/src/inpage/provider/initializeInpageProvider.ts
  extension/src/inpage/provider/messages.ts
  extension/src/inpage/provider/middleware/createRpcWarningMiddleware.ts
  extension/src/inpage/provider/utils.ts
  extension/src/inpage/types.ts
  extension/src/inpage/utils.ts
  yarn.lock
Labels: enhancement

#346 Lazy window.ethereum
  extension/src/background/index.ts
  extension/src/inpage/provider.ts
Labels: feature

#314 Implement basic price feeds
  Cargo.lock
  Cargo.toml
  bin/iron/Cargo.toml
  crates/exchange-rates/Cargo.toml
  crates/exchange-rates/res/feeds.json
  crates/exchange-rates/src/feed.rs
  crates/exchange-rates/src/init.rs
  crates/exchange-rates/src/lib.rs
Labels: feature

#334 Better settings and sidebars
  bin/iron/src/app.rs
  gui/src/components/AddressView.tsx
  gui/src/components/CommandBar.tsx
  gui/src/components/CommandBarButton.tsx
  gui/src/components/Navbar.tsx
  gui/src/components/NewVersionNotice.tsx
  gui/src/components/Settings/Settings.tsx
  gui/src/components/SettingsButton.tsx
  gui/src/components/Sidebar.tsx
  gui/src/global.d.ts
  gui/src/hooks/index.ts
  gui/src/hooks/useMenuAction.ts
  gui/src/store/index.ts
  gui/src/store/settingsWindow.ts
  gui/src/store/theme.ts
Labels: enhancement

#353 fixed extension yarn setup
  package.json
Labels: bugfix

#350 Adding etherscan API key setting
  crates/settings/src/lib.rs
  gui/src/components/Settings/General.tsx
  gui/src/types.ts
Labels: feature

#355 Clean up extension code
  extension/e2e/test.e2e.ts
  extension/package.json
  extension/src/background/index.ts
  extension/src/content-script/index.ts
  extension/src/inpage/index.ts
  extension/src/inpage/provider.ts
  extension/src/inpage/types.ts
  gui/src/components/QuickAddressSelect.tsx
  yarn.lock
Labels: refactor

#297 Add contract store
  Cargo.lock
  Cargo.toml
  bin/iron/src/app.rs
  bin/iron/tauri.conf.json
  crates/db/Cargo.toml
  crates/db/src/commands.rs
  crates/db/src/error.rs
  crates/db/src/lib.rs
  crates/db/src/queries.rs
  crates/db/src/utils.rs
  crates/exchange-rates/src/init.rs
  crates/exchange-rates/src/lib.rs
  crates/settings/src/error.rs
  crates/settings/src/lib.rs
  crates/sync/alchemy/src/error.rs
  crates/types/src/lib.rs
  crates/types/src/stored_contract.rs
  crates/types/src/ui_events.rs
  gui/src/components/Contracts.tsx
  gui/src/components/HomePage.tsx
  gui/src/components/LivenetPlaceholder.tsx
  gui/src/components/index.ts
  gui/src/hooks/index.ts
  gui/src/hooks/useRefreshContracts.ts
  gui/src/store/contracts.ts
  gui/src/store/index.ts
  gui/src/types.ts
  migrations/11_remove_deployed_code_from_contracts.sql
  migrations/12_add_abi_and_name_to_contracts.sql
Labels: feature

#356 Fix a long-standing bug where cs <> bg communication would sometimes fail
  extension/package.json
  extension/src/background/index.ts
  extension/src/content-script/index.ts
  extension/src/inpage/index.ts
  extension/src/inpage/provider.ts
  yarn.lock
Labels: bugfix

#361 Better extension build system
  .github/workflows/extension.yml
  .github/workflows/release.yml
  extension/README.md
  extension/__mocks__/webextension-polyfill.ts
  extension/e2e/test.e2e.ts
  extension/package.json
  extension/scripts/build.sh
  extension/src/public/manifest-chrome.json
  extension/src/public/manifest-firefox.json
  extension/vite/background.ts
  extension/vite/base.ts
  extension/vite/content.ts
  extension/vite/inpage.ts
  extension/wdio.conf.ts
  extension/wdio.e2e.conf.ts
  extension/wdio.ui.conf.ts
  yarn.lock
Labels: refactor
