Repository ethui/ethui, pull requests merged in 2023-06, with the labels that each got.

#217 Setting up libsodium on windows
  .github/workflows/release.yml
Labels: chore

#202 Ability to fetch ERC20 balances from alchemy.com
  Cargo.lock
  tauri/Cargo.toml
  tauri/src/alchemy/commands.rs
  tauri/src/alchemy/error.rs
  tauri/src/alchemy/global.rs
  tauri/src/alchemy/mod.rs
  tauri/src/app.rs
  tauri/src/db/mod.rs
  tauri/src/main.rs
  tauri/src/settings/mod.rs
Labels: backend

#216 add text field for alchemy api key in ui settings
  gui/src/components/SettingsGeneral.tsx
  gui/src/types.ts
Labels: feature, on-hold

#206 Add NewVersionNotice
  gui/src/components/HomePage.tsx
  gui/src/components/NewVersionNotice.tsx
Labels: feature

#257 Removing explicit usage of reqwest
  Cargo.lock
  tauri/Cargo.toml
  tauri/src/alchemy/error.rs
  tauri/src/alchemy/mod.rs
  tauri/src/alchemy/types.rs
  tauri/src/types/checksummed_address.rs
Labels: enhancement

#260 caching tx status on DB
  gui/src/components/Txs.tsx
  gui/src/types.ts
  migrations/08_add_status_to_transactions.sql
  tauri/src/block_listener/error.rs
  tauri/src/block_listener/expanders.rs
  tauri/src/db/queries.rs
  tauri/src/types/events.rs
Labels: enhancement

#258 Storing tips per chain - For tracking transaction history
  migrations/09_create_tips.sql
  tauri/src/db/mod.rs
  tauri/src/db/queries.rs
Labels: enhancement

#259 Alchemy transactions
  gui/src/components/HomePage.tsx
  gui/src/store/balances.ts
  tauri/src/alchemy/commands.rs
  tauri/src/alchemy/error.rs
  tauri/src/alchemy/mod.rs
  tauri/src/alchemy/types.rs
  tauri/src/alchemy/utils.rs
  tauri/src/app.rs
  tauri/src/block_listener/expanders.rs
  tauri/src/db/mod.rs
  tauri/src/db/queries.rs
  tauri/src/settings/commands.rs
  tauri/src/settings/mod.rs
Labels: feature

#262 Balances metadata #2
  gui/src/components/BalancesList.tsx
  gui/src/store/balances.ts
  gui/src/types.ts
  migrations/10_create_tokens_metadata.sql
  tauri/src/abis.rs
  tauri/src/alchemy/commands.rs
  tauri/src/alchemy/error.rs
  tauri/src/alchemy/mod.rs
  tauri/src/alchemy/utils.rs
  tauri/src/db/commands.rs
  tauri/src/db/mod.rs
  tauri/src/db/queries.rs
  tauri/src/types/mod.rs
  tauri/src/types/tokens.rs
Labels: enhancement

#264 Fixing wallet switch & refresh
  gui/src/components/Txs.tsx
Labels: bugfix

#263 Handling JsonRpcError
  tauri/src/alchemy/error.rs
Labels: bugfix

#266 updating release-drafter config
  .github/release-drafter.yml
Labels: chore

#268 Stopping event propagation in modals and contextmenus
  gui/src/components/ContextMenu.tsx
  gui/src/components/Modal.tsx
  gui/src/components/Txs.tsx
Labels: bugfix

#270 Fixing WagmiWrapper
  gui/src/components/WagmiWrapper.tsx
Labels: bugfix

#271 bugfix: modals in forms were broken
  gui/src/components/Modal.tsx
Labels: bugfix

#272 Indexing internal and token transfers from alchemy.com
  tauri/src/alchemy/mod.rs
Labels: feature

#273 Buffering alchemy transfers and notifying UI periodically
  tauri/src/alchemy/mod.rs
  tauri/src/alchemy/utils.rs
Labels: enhancement
