Repository ethui/ethui, pull requests merged in 2023-10, with the labels that each got.

#394 Adds no-confusing-void-expression to eslint
  .eslintrc.js
  extension/src/inpage/utils.ts
  gui/src/hooks/useNoticeAlchemyKeyMissing.tsx
Labels: chore

#396 Update metamask's dependencies
  .tool-versions
  extension/package.json
  extension/src/inpage/provider.ts
  extension/src/inpage/types.ts
  extension/src/inpage/utils.ts
  yarn.lock
Labels: chore

#399 iron_forge: proper error return type
  crates/forge/src/commands.rs
  crates/forge/src/error.rs
Labels: refactor

#400 Renames foundry_get_abi to forge_get_abi
  bin/iron/src/app.rs
  crates/forge/src/commands.rs
  crates/http/src/routes/forge.rs
  gui/src/components/Contracts.tsx
Labels: refactor

#404 Using node20 on CI
  .github/workflows/extension.yml
  .github/workflows/release.yml
  .github/workflows/yarn.yml
Labels: chore

#403 Enforce import organization with eslint
  .eslintrc.js
  .prettierrc.js
  extension/scripts/start.js
  extension/src/background/index.ts
  extension/src/inpage/index.ts
  extension/src/inpage/provider.ts
  extension/src/options/index.ts
  extension/vite/background.ts
  extension/vite/base.ts
  extension/vite/content.ts
  extension/vite/inpage.ts
  gui/src/App.tsx
  gui/src/components/CommandBar.tsx
  gui/src/components/ConfirmationDialog.tsx
  gui/src/components/NestedRoutes.tsx
  gui/src/components/Settings/Network.tsx
  gui/src/components/Settings/Wallet/HDWallet.tsx
  gui/src/components/Settings/Wallet/Impersonator.tsx
  gui/src/components/WagmiWrapper.tsx
  gui/src/components/index.ts
  gui/src/hooks/index.ts
  gui/src/hooks/tauri.ts
  gui/src/main.tsx
  gui/src/store/balances.ts
  gui/src/store/contracts.ts
  gui/src/store/index.ts
  gui/src/store/networks.ts
  gui/src/store/settings.ts
  gui/src/store/settingsWindow.ts
  gui/src/store/theme.ts
  gui/src/store/wallets.ts
  package.json
  yarn.lock
Labels: chore

#407 enforcing eslint import/export rules
  .eslintrc.js
  Justfile
  crates/http/src/routes/forge.rs
  crates/http/src/routes/mod.rs
  crates/wallets/src/commands.rs
  crates/wallets/src/utils.rs
  extension/src/content-script/index.ts
  extension/vite/base.ts
  gui/src/components/Connections.tsx
  gui/src/components/HomePage.tsx
  gui/src/components/IconCrypto.tsx
  gui/src/components/Onboarding/Carousel.tsx
  gui/src/components/Onboarding/Steps.tsx
  gui/src/components/Onboarding/index.tsx
  gui/src/components/Sidebar.tsx
  gui/src/components/index.ts
  gui/src/hooks/index.ts
  package.json
  tsconfig.json
Labels: chore

#410 Enforce no typescript relative-imports, except for sibling files
  .eslintrc.js
  extension/scripts/start.js
  extension/tsconfig.json
  gui/package.json
  gui/src/App.tsx
  gui/src/components/Onboarding/Wizard.tsx
  gui/src/components/Onboarding/Wrapper.tsx
  gui/src/components/Settings/General.tsx
  gui/src/components/Settings/Network.tsx
  gui/src/components/Settings/Wallet/HDWallet.tsx
  gui/src/components/Settings/Wallet/Impersonator.tsx
  gui/src/components/Settings/Wallet/JsonKeystore.tsx
  gui/src/components/Settings/Wallet/Plaintext.tsx
  gui/src/components/Settings/Wallets.tsx
  gui/src/hooks/useNoticeNewVersion.tsx
  gui/test/demo.test.tsx
  gui/test/setup.ts
  gui/tsconfig.json
  gui/vite.config.ts
  tsconfig.json
  yarn.lock
Labels: chore

#413 Removing rust warnings
  bin/iron/src/app.rs
Labels: chore

#416 Fix: ABIForm keeping values when changing target functions
  gui/src/components/ABIForm.tsx
Labels: bugfix

#422 nest Dialog components into their own subdir
  gui/src/App.tsx
  gui/src/components/Dialogs/Layout.tsx
  gui/src/components/Dialogs/MsgSign.tsx
  gui/src/components/Dialogs/TxReview.tsx
  gui/src/components/Dialogs/WalletUnlock.tsx
  gui/src/components/Dialogs/index.tsx
  gui/src/components/index.ts
Labels: refactor

#423 use abitype to decode abi in forms
  gui/package.json
  gui/src/components/ABIForm.tsx
  gui/src/types.ts
  yarn.lock
Labels: refactor

#401 HTTP API
  Cargo.lock
  bin/iron/src/app.rs
  crates/http/Cargo.toml
  crates/http/src/error.rs
  crates/http/src/init.rs
  crates/http/src/lib.rs
  crates/http/src/routes/connections.rs
  crates/http/src/routes/contracts.rs
  crates/http/src/routes/forge.rs
  crates/http/src/routes/mod.rs
  crates/http/src/routes/networks.rs
  crates/http/src/routes/rpc.rs
  crates/http/src/routes/settings.rs
  crates/http/src/routes/simulator.rs
  crates/http/src/routes/wallets.rs
  crates/http/src/routes/ws.rs
  crates/simulator/src/lib.rs
  crates/simulator/tests/detris.rs
  gui/src/components/ABIForm.tsx
  gui/src/components/Contracts.tsx
  gui/src/hooks/fetcher.ts
  gui/src/hooks/index.ts
  gui/src/hooks/useApi.ts
Labels: refactor

#439 Implement `/iron/db/` endpoints
  Cargo.lock
  crates/db/src/lib.rs
  crates/db/src/utils.rs
  crates/http/Cargo.toml
  crates/http/src/routes/db.rs
  crates/http/src/routes/internals.rs
  crates/http/src/routes/mod.rs
  crates/http/src/routes/sync.rs
Labels: refactor

#443 Implement `/iron/transactions/` endpoints
  crates/http/src/error.rs
  crates/http/src/routes/mod.rs
  crates/http/src/routes/transactions.rs
Labels: refactor

#445 Refactor iron-http to hide insecure routes behind feature flag
  crates/http/Cargo.toml
  crates/http/src/init.rs
  crates/http/src/routes/connections.rs
  crates/http/src/routes/mod.rs
Labels: refactor

#447 Dedicated foundry settings page
  crates/http/src/routes/settings.rs
  crates/settings/src/commands.rs
  crates/settings/src/lib.rs
  gui/src/components/Settings/Foundry.tsx
  gui/src/components/Settings/General.tsx
  gui/src/components/Settings/Settings.tsx
  gui/src/types.ts
Labels: feature

#450 Remove abi watch field
  crates/broadcast/src/lib.rs
  crates/http/src/routes/mod.rs
  gui/src/components/Settings/Foundry.tsx
Labels: refactor

#451 Testing alchemy and etherscan API keys
  bin/iron/src/app.rs
  crates/settings/src/commands.rs
  crates/settings/src/lib.rs
  crates/settings/src/utils.rs
  gui/src/components/Settings/General.tsx
Labels: feature

#455 Fix typos
  README.md
Labels: chore

#454 Fix extension build script to be compatible with MacOS
  extension/scripts/build.sh
Labels: bugfix

#452 Refactor ABIForm to sort and group options in Autocomplete
  gui/src/components/ABIForm.tsx
Labels: refactor

#456 Ability to send transactions via scripts
  crates/http/src/routes/mod.rs
  crates/http/src/routes/simulator.rs
  crates/http/src/routes/transactions.rs
  examples/scripts/sign-and-send.sh
  examples/scripts/simulate.sh
Labels: feature

#458 Stabilizes extension connection
  extension/package.json
  extension/src/background/index.ts
  yarn.lock
Labels: bugfix

#457 add json view to tx review dialog
  crates/broadcast/src/lib.rs
  crates/forge/src/commands.rs
  crates/forge/src/manager.rs
  crates/rpc/src/send_transaction.rs
  crates/settings/src/utils.rs
  gui/src/components/Calldata.tsx
  gui/src/components/Dialogs/TxReview.tsx
  gui/src/components/Txs.tsx
  gui/src/components/index.ts
Labels: chore

#463 Fixes pending TS warnings preventing GUI build
  .gitignore
  gui/src/components/ABIForm.tsx
  gui/src/components/Contracts.tsx
  gui/src/components/QuickAddressSelect.tsx
  gui/src/components/Settings/Wallet/HDWallet.tsx
  gui/src/components/Settings/Wallet/Plaintext.tsx
  gui/src/components/Settings/Wallets.tsx
  gui/src/store/balances.ts
  gui/src/store/wallets.ts
  gui/src/types.ts
  gui/vite.config.ts
Labels: bugfix

#460 Fix stuck onboarding
  crates/http/src/routes/settings.rs
Labels: bugfix

#464 Reset anvil tracker on every loop iteration
  crates/sync/anvil/src/tracker.rs
Labels: enhancement

#466 Fixing native balance not displaying on anvil networks
  Cargo.lock
  bin/iron/src/app.rs
  crates/sync/Cargo.toml
  crates/sync/alchemy/src/utils.rs
  crates/sync/anvil/src/error.rs
  crates/sync/anvil/src/expanders.rs
  crates/sync/anvil/src/lib.rs
  crates/sync/anvil/src/utils.rs
  crates/sync/src/commands.rs
  crates/sync/src/error.rs
  crates/sync/src/lib.rs
  crates/types/src/events.rs
  gui/src/store/balances.ts
Labels: bugfix

#465 Fixing a few todos
  Cargo.lock
  crates/connections/src/commands.rs
  crates/db/src/lib.rs
  crates/dialogs/Cargo.toml
  crates/dialogs/src/handle.rs
  crates/networks/src/commands.rs
  crates/sync/alchemy/src/lib.rs
  crates/wallets/src/plaintext.rs
  gui/src/components/Settings/Foundry.tsx
  gui/src/components/Settings/General.tsx
  gui/src/components/Settings/Network.tsx
  gui/src/components/Settings/Wallet/HDWallet.tsx
  gui/src/store/networks.ts
Labels: chore
