Repository ethui/ethui, pull requests merged in 2023-09, with the labels that each got.

#351 Refactors OSX menu logic
  bin/iron/src/app.rs
  bin/iron/src/main.rs
  bin/iron/src/menu.rs
  bin/iron/src/system_tray.rs
Labels: refactor

#326 Setup extension publishing on CI
  .github/workflows/release.yml
  extension/package.json
  extension/scripts/build.sh
Labels: chore

#380 Auto reloading basic settings such as dark mode
  Cargo.lock
  crates/settings/Cargo.toml
  crates/settings/src/commands.rs
  crates/settings/src/lib.rs
  crates/types/src/ui_events.rs
  gui/src/components/Peers.tsx
  gui/src/components/Settings/General.tsx
  gui/src/components/Txs.tsx
  gui/src/hooks/index.ts
  gui/src/hooks/useEventListener.ts
  gui/src/store/index.ts
  gui/src/store/settings.ts
  gui/src/store/theme.ts
Labels: bugfix

#325 Erc721 list - backend
  Cargo.lock
  bin/iron/src/app.rs
  crates/abis/src/lib.rs
  crates/db/src/commands.rs
  crates/db/src/lib.rs
  crates/db/src/queries.rs
  crates/sync/anvil/Cargo.toml
  crates/sync/anvil/src/error.rs
  crates/sync/anvil/src/tracker.rs
  crates/types/src/lib.rs
  crates/types/src/tokens.rs
  crates/types/src/ui_events.rs
  migrations/13_create_nfts_metadata.sql
Labels: feature

#384 Fixing nested btn error
  gui/src/components/AddressView.tsx
Labels: bugfix

#381 Expanded view for transactions
  gui/package.json
  gui/src/App.tsx
  gui/src/components/MonoText.tsx
  gui/src/components/Txs.tsx
  gui/src/components/index.ts
  gui/src/global.css
  gui/src/main.tsx
  yarn.lock
Labels: feature

#393 Fixing random vite cache issues
  .github/workflows/extension.yml
  gui/package.json
  gui/src/components/CommandBarButton.tsx
  gui/src/components/Onboarding/Carousel.tsx
  gui/src/components/SettingsButton.tsx
  gui/src/components/Sidebar.tsx
  gui/src/components/index.ts
  gui/src/hooks/useNoticeAlchemyKeyMissing.tsx
Labels: chore, bugfix
