Repository ethui/ethui, pull requests merged in 2023-12, with the labels that each got.

#548 Fixes ping-pong keepalive logic
  crates/ws/src/server.rs
  extension/src/background/index.ts
Labels: bugfix

#488 In wallet transfers
  gui/src/components/Account.tsx
  gui/src/components/BalancesList.tsx
  gui/src/components/Inputs/BigIntField.tsx
  gui/src/components/Inputs/index.tsx
  gui/src/components/Transfer.tsx
  gui/src/components/TransferForm.tsx
  gui/src/components/index.ts
  gui/src/store/balances.ts
  gui/src/types/wallets.ts
Labels: feature

#556 Fixing live reload
  Cargo.toml
  Justfile
Labels: chore

#559 chain icons in kbar actions
  gui/src/components/Sidebar.tsx
  gui/src/store/networks.tsx
Labels: enhancement

#560 Cleaning up sidebar styles + transitions
  gui/src/components/CommandBarButton.tsx
  gui/src/components/SettingsButton.tsx
  gui/src/components/Sidebar.tsx
  gui/src/components/SidebarButton.tsx
  gui/src/components/index.ts
  gui/src/store/theme.ts
Labels: enhancement

#555 rpc: wallet_addEthereumChain
  Cargo.lock
  Cargo.toml
  bin/iron/src/dialogs.rs
  crates/dialogs/src/presets.rs
  crates/dialogs/src/utils.rs
  crates/networks/src/lib.rs
  crates/rpc/Cargo.toml
  crates/rpc/src/error.rs
  crates/rpc/src/lib.rs
  crates/rpc/src/methods/chain_add.rs
  crates/rpc/src/methods/mod.rs
  crates/rpc/src/methods/send_transaction.rs
  crates/rpc/src/methods/sign_message.rs
  crates/simulator/Cargo.toml
  crates/simulator/tests/detris.rs
  gui/src/App.tsx
  gui/src/components/Dialogs/ChainAdd.tsx
  gui/src/components/Dialogs/index.tsx
  gui/src/components/Icons/Chain.tsx
  gui/src/components/QuickNetworkSelect.tsx
  gui/src/hooks/useDialog.ts
  gui/src/store/networks.tsx
Labels: feature

#562 Moving a few more components to the storybook
  .eslintrc.js
  gui/package.json
  gui/src/App.tsx
  gui/src/components/AddressView.tsx
  gui/src/components/Connections.tsx
  gui/src/components/ContextMenu.tsx
  gui/src/components/ContextMenuWithTauri.tsx
  gui/src/components/Dialogs/ChainAdd.tsx
  gui/src/components/Dialogs/TxReview.tsx
  gui/src/components/QuickNetworkSelect.tsx
  gui/src/components/Settings/Network.tsx
  gui/src/components/Sidebar.tsx
  gui/src/components/TransferForm.tsx
  gui/src/components/Txs.tsx
  gui/src/components/index.ts
  gui/src/store/networks.tsx
  gui/src/store/theme.ts
  package.json
  packages/components/index.ts
  packages/react/.eslintrc.cjs
  packages/react/.storybook/main.ts
  packages/react/.storybook/preview.ts
  packages/react/components/Button/index.tsx
  packages/react/components/Button/stories.tsx
  packages/react/components/ChainView/index.tsx
  packages/react/components/ChainView/stories.tsx
  packages/react/components/ClickToCopy/index.tsx
  packages/react/components/ClickToCopy/stories.tsx
  packages/react/components/ContextMenu/index.tsx
  packages/react/components/ContextMenu/stories.tsx
  packages/react/components/icons/Chain.stories.tsx
  packages/react/components/icons/Chain.tsx
  packages/react/components/icons/index.ts
  packages/react/components/index.ts
  packages/react/components/inputs/BigIntField.stories.tsx
  packages/react/components/inputs/BigIntField.tsx
  packages/react/components/inputs/index.ts
  packages/react/global.d.ts
  packages/react/images/chains/1.svg
  packages/react/images/chains/1.webp
  packages/react/images/chains/10.webp
  packages/react/images/chains/31337.webp
  packages/react/images/chains/unknown.png
  packages/react/images/chains/unknown.webp
  packages/react/index.ts
  packages/react/package.json
  packages/react/themes.ts
  packages/react/tsconfig.json
  packages/react/utils.ts
  packages/react/vite-env.d.ts
  packages/react/vite.config.ts
  yarn.lock
Labels: refactor

#563 Move typography and MonoText to storybook
  gui/src/components/AddressView.tsx
  gui/src/components/Calldata.tsx
  gui/src/components/ErrorHandler.tsx
  gui/src/components/MonoText.tsx
  gui/src/components/index.ts
  gui/src/store/networks.tsx
  gui/tsconfig.json
  packages/react/.storybook/preview.ts
  packages/react/@types/global.d.ts
  packages/react/components/ChainView/index.tsx
  packages/react/components/Typography/index.tsx
  packages/react/components/Typography/stories.tsx
  packages/react/components/index.ts
  packages/react/global.d.ts
  packages/react/package.json
  packages/react/themes.ts
  packages/react/tsconfig.json
  yarn.lock
Labels: refactor

#566 feat: private key wallets
  crates/simulator/tests/detris.rs
  crates/wallets/src/wallet.rs
  crates/wallets/src/wallets/mod.rs
  crates/wallets/src/wallets/private_key.rs
  gui/src/components/QuickAddressSelect.tsx
  gui/src/components/Settings/Wallet/PrivateKey.tsx
  gui/src/components/Settings/Wallets.tsx
  packages/types/wallets.ts
Labels: feature

#567 Using skeletons in tx view to fix reveal animation
  gui/src/components/Datapoint.tsx
  gui/src/components/Txs.tsx
Labels: bugfix

#576 Refactor home layout
  gui/src/App.tsx
  gui/src/components/Home/Layout.tsx
  gui/src/components/Home/Navbar.tsx
  gui/src/components/Home/Sidebar.tsx
  gui/src/components/Home/index.tsx
  gui/src/components/HomePage.tsx
  gui/src/components/Sidebar.tsx
  gui/src/components/index.ts
Labels: refactor
