Repository ethui/ethui, pull requests merged in 2024-10, with the labels that each got.

#714 Collection of small improvements (scroll, deps, bypass enable)
  Cargo.lock
  Cargo.toml
  crates/simulator/src/evm.rs
  crates/sync/alchemy/src/networks.rs
  extension/src/inpage/provider.ts
  packages/react/components/icons/Chain.tsx
  packages/react/images/chains/534351.webp
  packages/react/images/chains/534352.webp
Labels: enhancement

#717 Ability to overwrite config dir
  .mise.toml
  bin/src/app.rs
  crates/args/src/lib.rs
Labels: feature

#721 Nix build support
  .gitignore
  .mise/tasks/sqlx
  examples/scripts/sign-and-send.sh
  examples/scripts/simulate.sh
  extension/scripts/build.sh
  flake.lock
  flake.nix
  icons/generate.sh
Labels: chore

#722 Updating alloy and foundry
  Cargo.lock
  Cargo.toml
  crates/abis/Cargo.toml
  crates/broadcast/Cargo.toml
  crates/rpc/Cargo.toml
  crates/rpc/src/methods/send_transaction.rs
  crates/simulator/Cargo.toml
  crates/simulator/src/types.rs
  crates/simulator/tests/detris.rs
  crates/types/Cargo.toml
  crates/types/src/lib.rs
  crates/types/src/to_alloy.rs
Labels: dependencies

#726 TODO workflow
  .github/workflows/todos.yml
Labels: chore

#728 ethui_settings: ethers->alloy
  Cargo.lock
  Cargo.toml
  crates/settings/Cargo.toml
  crates/settings/src/utils.rs
  flake.nix
Labels: dependencies

#729 warning for unused variable
  crates/exchange-rates/src/feed.rs
Labels: chore

#731 sync_alchemy: ethers -> alloy
  .mise.toml
  Cargo.lock
  crates/sync/alchemy/Cargo.toml
  crates/sync/alchemy/src/client.rs
  crates/sync/alchemy/src/error.rs
  crates/sync/alchemy/src/lib.rs
  crates/sync/alchemy/src/networks.rs
  crates/sync/alchemy/src/types.rs
  crates/sync/src/worker.rs
Labels: dependencies

#733 cargo nextest
  .github/workflows/rust.yml
  bacon.toml
  crates/simulator/tests/detris.rs
  crates/wallets/src/utils.rs
Labels: dependencies

#734 testing wallet in-memory secrets
  Cargo.lock
  Cargo.toml
  crates/abis/Cargo.toml
  crates/wallets/Cargo.toml
  crates/wallets/src/wallets/hd_wallet.rs
  crates/wallets/src/wallets/json_keystore_wallet.rs
Labels: chore

#735 Fixing events not reaching secondary webviews
  Cargo.lock
  Cargo.toml
  bin/src/dialogs.rs
  gui/src/hooks/useDialog.ts
  gui/src/hooks/useEventListener.ts
  gui/src/routes/_dialog.dialog/tx-review.$id.tsx
Labels: bug

#736 Fixing dialogs
  bin/src/dialogs.rs
  gui/package.json
  gui/src/hooks/useDialog.ts
  gui/src/routes/_dialog.dialog/tx-review.$id.tsx
  yarn.lock
Labels: bugfix

#732 ethui_wallets: ethers-rs -> alloy
  Cargo.lock
  Cargo.toml
  bacon.toml
  crates/crypto/Cargo.toml
  crates/rpc/src/error.rs
  crates/rpc/src/lib.rs
  crates/rpc/src/methods/send_transaction.rs
  crates/rpc/src/methods/sign_message.rs
  crates/simulator/src/evm.rs
  crates/simulator/src/types.rs
  crates/simulator/tests/detris.rs
  crates/wallets/Cargo.toml
  crates/wallets/src/error.rs
  crates/wallets/src/signer.rs
  crates/wallets/src/utils.rs
  crates/wallets/src/wallets/hd_wallet.rs
  crates/wallets/src/wallets/json_keystore_wallet.rs
  crates/wallets/src/wallets/ledger.rs
  crates/wallets/src/wallets/plaintext.rs
  crates/wallets/src/wallets/private_key.rs
  gui/src/hooks/useDialog.ts
  gui/src/routes/_dialog.dialog/tx-review.$id.tsx
Labels: dependencies

#738 Improve workflow skip rules
  .github/workflows/extension.yml
  .github/workflows/release-drafter.yml
  .github/workflows/rust.yml
  .github/workflows/yarn.yml
Labels: chore

#739 Removes http crate (currently unused)
  Cargo.lock
  Cargo.toml
  bin/Cargo.toml
  bin/src/app.rs
  bin/src/error.rs
  bin/src/lib.rs
  crates/http/Cargo.toml
  crates/http/src/error.rs
  crates/http/src/init.rs
  crates/http/src/lib.rs
  crates/http/src/routes/connections.rs
  crates/http/src/routes/contracts.rs
  crates/http/src/routes/db.rs
  crates/http/src/routes/internals.rs
  crates/http/src/routes/mod.rs
  crates/http/src/routes/networks.rs
  crates/http/src/routes/rpc.rs
  crates/http/src/routes/settings.rs
  crates/http/src/routes/sync.rs
  crates/http/src/routes/transactions.rs
  crates/http/src/routes/ui.rs
  crates/http/src/routes/wallets.rs
  crates/http/src/routes/ws.rs
  crates/http/src/utils.rs
  gui/src/hooks/index.ts
  gui/src/hooks/useApi.ts
Labels: dependencies, chore

#742 Yarn upgrades
  bin/Cargo.toml
  extension/package.json
  gui/package.json
  package.json
  packages/abiparse/package.json
  packages/data/package.json
  packages/form/package.json
  packages/react/package.json
  packages/types/package.json
  yarn.lock
Labels: dependencies

#744 Fixes https://github.com/ethui/ethui/security/dependabot/75
  extension/package.json
  gui/package.json
  package.json
  yarn.lock
Labels: dependencies

#746 Fixes https://github.com/ethui/ethui/security/dependabot/80
  gui/package.json
  yarn.lock
Labels: dependencies

#747 Upgrade to material v6
  gui/package.json
  gui/src/components/ABIForm/ABIItemForm.tsx
  gui/src/components/CommandBar.tsx
  gui/src/components/Datapoint.tsx
  gui/src/routes/_dialog.dialog/chain-add.$id.tsx
  gui/src/routes/_dialog.dialog/erc1155-add.$id.tsx
  gui/src/routes/_dialog.dialog/erc20-add.$id.tsx
  gui/src/routes/_dialog.dialog/erc721-add.$id.tsx
  gui/src/routes/_dialog.dialog/tx-review.$id.tsx
  gui/src/routes/_home.home/transactions.lazy.tsx
  packages/form/src/AbiForm.tsx
  packages/react/package.json
  yarn.lock
Labels: dependencies

#749 A few more package upgrades
  extension/package.json
  gui/package.json
  packages/abiparse/package.json
  packages/data/package.json
  packages/form/package.json
  packages/react/package.json
  packages/types/package.json
  yarn.lock
Labels: dependencies

#750 metamask packages updated
  extension/package.json
  yarn.lock
Labels: dependencies

#751 Node 22
  .github/workflows/extension.yml
  .github/workflows/release.yml
  .github/workflows/yarn.yml
  .mise.toml
  extension/package.json
  gui/package.json
  gui/src/components/ABIForm/ABIItemForm.tsx
  gui/src/routes/_dialog.dialog/tx-review.$id.tsx
  packages/data/package.json
  packages/form/src/AbiForm.tsx
  packages/types/package.json
  yarn.lock
Labels: dependencies

#754 Fixing release builds
  bin/src/app.rs
Labels: bugfix
