Repository ethui/ethui, pull requests merged in 2024-06, with the labels that each got.

#682 Fixing clippy lints
  crates/sync/alchemy/src/lib.rs
Labels: chore

#681 missing react key on general settings
  packages/react/components/Form/index.tsx
Labels: bugfix

#683 fix: Return value of view functions
  gui/src/components/ABIForm/ABIItemForm.tsx
Labels: bugfix

#680 Fix: filter contracts by alias
  gui/src/store/contracts.ts
  packages/types/index.ts
Labels: bugfix

#677 Change Sign Message dialog UI
  crates/dialogs/src/presets.rs
  gui/src/routes/_dialog.dialog/msg-sign.$id.tsx
Labels: enhancement

#687 updating web-ext to 8.x.x
  .github/workflows/release.yml
  extension/package.json
  extension/scripts/build.sh
  package.json
  yarn.lock
Labels: chore

#688 update ws. fixes advisory #58
  gui/package.json
  package.json
  packages/data/package.json
  packages/form/package.json
  packages/react/package.json
  packages/types/package.json
  yarn.lock
Labels: chore

#689 yarn upgrade-interactive
  .yarn/releases/yarn-4.0.2.cjs
  .yarn/releases/yarn-4.3.1.cjs
  .yarnrc.yml
  extension/package.json
  gui/package.json
  package.json
  packages/abiparse/package.json
  packages/data/package.json
  packages/form/package.json
  packages/react/package.json
  packages/types/package.json
  yarn.lock
Labels: chore

#690 Fixes NaN on network name
  gui/src/components/Settings/Network.tsx
  gui/src/routeTree.gen.ts
  gui/src/routes/_home.home/connections.lazy.tsx
  gui/src/routes/_home.home/contracts.lazy.tsx
  gui/src/routes/_home.home/transactions.lazy.tsx
Labels: bugfix
