Repository ethui/ethui, pull requests merged in 2025-09, with the labels that each got.

#1416 Highlight addresses explorer
  gui/package.json
  gui/src/components/Transactions/TransactionsTable.tsx
  nix/package.nix
  pnpm-lock.yaml
Labels: A-feature

#1399 Explorer
  .sqlx/query-005fc32b4916aa4e4829e2357ed28648e7c555c7f69ffee67223db61bbff5d96.json
  .sqlx/query-28c888580ac4c9ab0b31aa2649e33d5b1d84f434c3580c0cb9a6860f53ff57dc.json
  .sqlx/query-4cd331ccab616c9243578d52614921d98459137aa0775344feb0b44ff20fcd49.json
  .sqlx/query-a6408e8b2377aa980e345959b19ea6544aaca0a9e838b0b7b3959b8ff788784a.json
  .sqlx/query-cb73d86f4cf30d8938a0b69679a93367a9f20053c1d48bb92e08a134efd85c91.json
  bin/src/app.rs
  crates/db/src/commands.rs
  crates/db/src/queries/contracts.rs
  crates/db/src/queries/transactions.rs
  crates/rpc/src/commands.rs
  crates/rpc/src/lib.rs
  crates/rpc/src/utils.rs
  crates/types/src/transactions.rs
  gui/package.json
  gui/src/components/AddressView.tsx
  gui/src/components/AppSidebar.tsx
  gui/src/components/HashView.tsx
  gui/src/components/Transactions/TransactionsTable.tsx
  gui/src/components/Transactions/TransactionsView.tsx
  gui/src/hooks/useAddressBalance.ts
  gui/src/hooks/useAddressTxs.ts
  gui/src/hooks/useAllAddresses.ts
  gui/src/hooks/useIsContract.ts
  gui/src/hooks/useLatestTxs.ts
  gui/src/routeTree.gen.ts
  gui/src/routes/home/_l/explorer/_l.tsx
  gui/src/routes/home/_l/explorer/_l/addresses/$address.tsx
  gui/src/routes/home/_l/explorer/_l/addresses/index.tsx
  gui/src/routes/home/_l/explorer/_l/transactions/$transaction.tsx
  gui/src/routes/home/_l/explorer/_l/transactions/index.tsx
  gui/src/routes/home/_l/transactions.tsx
  gui/src/utils.ts
  nix/package.nix
  pnpm-lock.yaml
Labels: A-feature

#1428 fix: anvil CaughtUp msg was never being sent
  crates/simulator/tests/detris.rs
  crates/sync/anvil/src/tracker/worker.rs
Labels: B-bugfix

#1429 fix: nullable network fields
  gui/package.json
  gui/src/routes/home/_l/settings/_l/networks/_l/$name.edit.tsx
  gui/src/routes/home/_l/settings/_l/networks/_l/new.tsx
  nix/package.nix
  packages/types/network.ts
  pnpm-lock.yaml
Labels: B-bugfix

#1430 Add navigation buttons top bar
  gui/src/components/Topbar.tsx
Labels: A-feature

#1431 Automatically fix nix pnpm hashes for dependabot PRs
  .github/workflows/check-nix-hashes.yml
Labels: C-chore

#1432 General updates (description)
  gui/src/components/AddressView.tsx
  gui/src/components/AppSidebar.tsx
  gui/src/components/Breadcrumbs.tsx
  gui/src/components/ContractCallForm.tsx
  gui/src/components/ERC20View.tsx
  gui/src/components/EmptyState.tsx
  gui/src/components/Topbar.tsx
  gui/src/components/Transactions/TransactionsTable.tsx
  gui/src/components/Transactions/TransactionsView.tsx
  gui/src/components/WalletSidebar/WalletSelector.tsx
  gui/src/components/WalletSidebar/index.tsx
  gui/src/hooks/useIsAnvilNetwork.ts
  gui/src/routeTree.gen.ts
  gui/src/routes/dialog/_l/erc1155-add.$id.tsx
  gui/src/routes/dialog/_l/erc20-add.$id.tsx
  gui/src/routes/dialog/_l/erc721-add.$id.tsx
  gui/src/routes/home/_l/account.tsx
  gui/src/routes/home/_l/connections.tsx
  gui/src/routes/home/_l/contracts/_l/$chainId.$address.tsx
  gui/src/routes/home/_l/explorer/_l/addresses/$address.tsx
  gui/src/routes/home/_l/explorer/_l/addresses/index.tsx
  gui/src/routes/home/_l/explorer/_l/contracts/_l.tsx
  gui/src/routes/home/_l/explorer/_l/contracts/_l/$chainId.$address.tsx
  gui/src/routes/home/_l/explorer/_l/contracts/_l/_l.add.tsx
  gui/src/routes/home/_l/explorer/_l/contracts/_l/index.tsx
  gui/src/routes/home/_l/explorer/_l/transactions/$transaction.tsx
  gui/src/routes/home/_l/settings/_l/tokens.tsx
  gui/src/routes/home/_l/transactions.tsx
Labels: A-enhancement

#1438 Explorer addresses tabs
  gui/src/hooks/useAllAddresses.ts
  gui/src/routes/home/_l/explorer/_l/addresses/index.tsx
Labels: A-feature
