Repository ethui/ethui, pull requests merged in 2025-05, with the labels that each got.

#1238 Adds etherscan API key to onboarding steps
  bin/src/windows/main.rs
  crates/settings/src/init.rs
  crates/settings/src/onboarding.rs
  gui/src/components/AppSidebar.tsx
  gui/src/routes/home/_l/onboarding.tsx
  packages/types/settings.ts
Labels: A-enhancement

#1239 Fixes breadcrumbs linking to empty pages
  gui/src/components/Breadcrumbs.tsx
  gui/src/routes/home/_l/settings/_l.tsx
  gui/src/routes/home/_l/transfer/_l.tsx
Labels: B-bugfix

#1241 Replaces checkboxes with switches
  gui/package.json
  gui/src/components/QuickFastModeToggle.tsx
  gui/src/routes/home/_l/settings/_l/general.tsx
  packages/form/package.json
  yarn.lock
Labels: A-enhancement

#1250 Update tauri on both rust and js sides
  Cargo.lock
  Cargo.toml
  bin/Cargo.toml
  gui/package.json
  package.json
  yarn.lock
Labels: C-dependencies, dependencies

#1251 Update alloy and foundry deps
  Cargo.lock
  Cargo.toml
  crates/simulator/src/evm.rs
Labels: dependencies

#1254 update @ethui/ui
  gui/package.json
  gui/src/components/Settings/Wallet/Ledger.tsx
  gui/src/components/Settings/Wallet/Plaintext.tsx
  gui/src/routes/home/_l/transfer/_l.erc20.tsx
  gui/src/routes/home/_l/transfer/_l.eth.tsx
  packages/abiparse/package.json
  packages/form/package.json
  packages/types/package.json
  packages/types/wallets.ts
  yarn.lock
Labels: dependencies

#1258 Small copy fix
  gui/src/components/Settings/Wallet/PrivateKey.tsx
Labels: B-bugfix

#1259 blockExplorerUrls should be optional
  crates/rpc/src/methods/chain_add.rs
  crates/rpc/src/methods/chain_update.rs
Labels: B-bugfix

#1263 Fix onboarding finish flow
  crates/settings/src/onboarding.rs
Labels: B-bugfix

#1252 adjust sidebar top padding on macos
  gui/src/components/AppSidebar.tsx
Labels: A-enhancement

#1267 Set minimum window size
  bin/src/windows/mod.rs
Labels: A-enhancement

#1270 Fixing some setup problems
  .mise/tasks/setup
Labels: C-chore

#1273 Fix removing proxy contract
  .sqlx/query-d252b85cc9a994333c656a26098634fda678998e854e48c50a478105f68b0a5b.json
  bin/src/commands.rs
  crates/db/src/queries/contracts.rs
Labels: B-bugfix
