Repository ethui/ethui, pull requests merged in 2025-01, with the labels that each got.

#879 No longer fetch 'internal' alchemy transfers
  crates/sync/alchemy/src/client.rs
Labels: B-bugfix

#884 Fix #875 - extension zip missing from release assets
  .github/workflows/release.yml
Labels: B-bugfix

#896 Add `db_insert_contract_with_etherscan` command
  bin/src/app.rs
  crates/db/src/commands.rs
  gui/src/store/useContracts.ts
Labels: A-refactor

#886 Fix extension icon color
  extension/manifest/base.json
Labels: B-bugfix

#885 Removes foundry-config dep
  Cargo.lock
  Cargo.toml
  crates/simulator/Cargo.toml
  crates/simulator/src/evm.rs
Labels: C-dependencies, C-chore

#900 Cleanup warning about no alchemy key
  bin/src/app.rs
  crates/rpc/src/lib.rs
  crates/sync/alchemy/src/utils.rs
  crates/sync/src/error.rs
  crates/sync/src/worker.rs
Labels: B-bugfix
