Repository ethui/ethui, pull requests merged in 2025-02, with the labels that each got.

#902 yarn upgrade-interactive
  extension/package.json
  gui/package.json
  package.json
  packages/abiparse/package.json
  packages/data/package.json
  packages/demo/package.json
  packages/form/package.json
  packages/types/package.json
  packages/ui/package.json
  yarn.lock
Labels: C-dependencies

#904 Upgrade to tauri 2.2
  Cargo.lock
  Cargo.toml
  gui/package.json
  package.json
  yarn.lock
Labels: C-dependencies, C-chore

#908 Upgrade vitest and ts-unused-exports
  extension/package.json
  gui/package.json
  package.json
  packages/abiparse/package.json
  packages/ui/package.json
  yarn.lock
Labels: C-dependencies, C-chore

#910 Updates metamask's packages
  extension/package.json
  yarn.lock
Labels: C-dependencies, C-chore

#914 Add proxy-detect crate as dependency
  Cargo.lock
  Cargo.toml
  bin/Cargo.toml
  deny.toml
Labels: C-dependencies

#916 wallet_addEthereumChain (EIP-3085)
  Cargo.lock
  crates/dialogs/Cargo.toml
  crates/dialogs/src/handle.rs
  crates/dialogs/src/presets.rs
  crates/networks/src/network.rs
  crates/rpc/src/lib.rs
  crates/rpc/src/methods/chain_add.rs
  crates/tracing/Cargo.toml
  crates/tracing/src/lib.rs
  gui/src/routes/dialog/_l/chain-add.$id.tsx
  mprocs.yaml
  packages/types/index.ts
Labels: A-EIPs, C-app

#917 rework of wallet_updateEthereumChain
  crates/broadcast/src/lib.rs
  crates/rpc/src/lib.rs
  crates/rpc/src/methods/chain_add.rs
  crates/rpc/src/methods/chain_update.rs
  crates/rpc/src/methods/mod.rs
  gui/src/components/QuickNetworkSelect.tsx
  gui/src/routeTree.gen.ts
  gui/src/routes/dialog/_l.tsx
  gui/src/routes/dialog/_l/chain-switch.$id.tsx
  gui/src/store/useNetworks.tsx
  packages/types/index.ts
Labels: A-feature, C-app

#918 using cargo-binstall sqlx instead of compiling from source
  .github/workflows/rust.yml
Labels: C-chore

#919 Clear affinities whenever a chain is removed
  crates/connections/src/init.rs
  crates/connections/src/store.rs
  crates/types/src/affinity.rs
Labels: B-bugfix, C-app

#920 no longer spawn demo in mprocs
  mprocs.yaml
Labels: C-chore, A-dx

#921 Deletes old references to http api
  bin/src/lib.rs
  crates/args/src/lib.rs
Labels: C-chore

#927 Fix proxy name and ABI assignment
  bin/src/commands.rs
Labels: B-bugfix

#929 Update contracts UI
  .sqlx/query-c3c23470236e006a58e2d34b145a5f5588dd9cca52a4adbbcd1367f6c58c5838.json
  .sqlx/query-c50a1204bf877666b7b5447a3b7ac83fae9694ab1a93d769f6f0d39defdd311c.json
  crates/db/src/queries/contracts.rs
  crates/types/src/contracts.rs
  gui/src/components/QuickNetworkSelect.tsx
  gui/src/routes/home/_l/contracts/_l/index.tsx
  gui/src/store/useContracts.ts
  packages/types/index.ts
Labels: A-feature, E-ui, C-app

#934 Remove zip from extension release
  .github/workflows/release.yml
Labels: B-bugfix

#933 Enforce labels from release drafter in Pull Requests
  .github/workflows/pr-lint.yml
Labels: C-chore

#937 Fixing extension release
  .github/workflows/release.yml
Labels: B-bugfix

#936 Update cargo.lock
  Cargo.lock
Labels: C-chore

#938 Update release drafter
  .github/workflows/release-drafter.yml
Labels: C-chore

#949 Fixes proxy detection on anvil
  .sqlx/query-bb395f26336f92302407fa80bfa7bcb0473e35ff123cb7a4c399b5faaf6f7dd2.json
  .sqlx/query-c04f674d4516b262ffede780de8ae867e3a9ad832723e38fdf77d6702f16b8c9.json
  Cargo.lock
  Cargo.toml
  crates/db/src/queries/contracts.rs
  crates/db/src/queries/events.rs
  crates/forge/src/utils.rs
  crates/sync/anvil/Cargo.toml
  crates/sync/anvil/src/error.rs
  crates/sync/anvil/src/expanders.rs
  crates/types/src/events.rs
Labels: B-bugfix

#957 Defaulting ws_url to same host as http
  crates/networks/src/network.rs
Labels: B-bugfix

#958 Resubscribe forge on contract creation
  crates/forge/src/init.rs
Labels: A-enhancement

#969 Command bar and sidebar fixes
  gui/src/components/QuickAddressSelect.tsx
  gui/src/components/QuickFastModeToggle.tsx
  gui/src/components/QuickWalletSelect.tsx
  gui/src/store/useSettings.ts
  gui/src/store/useWallets.ts
Labels: E-ui, B-bugfix

#971 Fix contract call form
  gui/src/components/ContractCallForm.tsx
Labels: B-bugfix

#972 Remove old storybook deps
  gui/package.json
  gui/src/components/Settings/Wallets.tsx
  yarn.lock
Labels: C-dependencies

#979 Save and restore sync status for Anvil chains
  crates/sync/anvil/src/tracker.rs
Labels: A-feature

#978 Reseting network when adding/removing/changing it
  crates/networks/src/lib.rs
  crates/networks/src/network.rs
Labels: B-bugfix

#1002 Fix PR lint action
  .github/workflows/pr-lint.yml
Labels: C-chore

#995 Move Network to `ethui_types`
  Cargo.lock
  crates/connections/src/ctx.rs
  crates/networks/src/commands.rs
  crates/networks/src/init.rs
  crates/networks/src/lib.rs
  crates/rpc/src/methods/chain_add.rs
  crates/rpc/src/methods/chain_update.rs
  crates/rpc/src/methods/send_call.rs
  crates/rpc/src/methods/send_transaction.rs
  crates/rpc/src/methods/sign_message.rs
  crates/types/Cargo.toml
  crates/types/src/lib.rs
  crates/types/src/network.rs
Labels: C-chore, A-refactor

#996 Update Network events
  crates/broadcast/src/lib.rs
  crates/connections/src/init.rs
  crates/db/src/init.rs
  crates/networks/src/lib.rs
  crates/rpc/src/methods/chain_add.rs
  crates/rpc/src/methods/send_transaction.rs
  crates/simulator/src/commands.rs
  crates/sync/src/commands.rs
  crates/sync/src/lib.rs
  crates/types/src/network.rs
Labels: C-chore, A-refactor

#986 Remove ResetAnvilListener
  crates/broadcast/src/lib.rs
  crates/networks/src/init.rs
  crates/networks/src/lib.rs
  crates/sync/anvil/src/error.rs
  crates/sync/anvil/src/init.rs
  crates/types/src/network.rs
Labels: C-chore, A-refactor

#1003 Prevent release drafter from creating duplicate drafts
  .github/workflows/release-drafter.yml
Labels: C-chore

#1029 Refactor the way github checks are skipped
  .github/workflows/nodejs.yml
  .github/workflows/rust.yml
Labels: C-chore

#1031 Codeowners
  CODEOWNERS
Labels: C-chore

#1030 cleanup old tanstack vite plugin
  gui/package.json
  yarn.lock
Labels: C-dependencies

#1035 Replace outdated infinite scroll component with custom one
  gui/package.json
  gui/src/routes/home/_l/transactions.tsx
  packages/types/index.ts
  yarn.lock
Labels: A-refactor

#1038 Smoother transaction infinite scroll and updates
  .sqlx/query-008400ee1a9cb21eda246d7ea2cc8e3440d4c8c27c8abd40fd16b6539956b935.json
  .sqlx/query-2f26c1c5367e742c378eb391dc14ee34d60ae2a592442eca0abc7196d2b5a18a.json
  .sqlx/query-8be4a03cd7356c7c1c3998fcb965deb348bc1e86f4f0b9b3f8b0f7f744e01a4b.json
  bin/src/app.rs
  crates/db/src/commands.rs
  crates/db/src/lib.rs
  crates/db/src/pagination.rs
  crates/db/src/queries/transactions.rs
  crates/types/src/transactions.rs
  gui/package.json
  gui/src/routes/home/_l/transactions.tsx
  packages/form/package.json
  packages/types/index.ts
  yarn.lock
Labels: A-feature

#1045 Migrating to tailwind v4
  gui/package.json
  gui/postcss.config.js
  gui/tailwind.config.js
  gui/vite.config.ts
  package.json
  yarn.lock
Labels: C-dependencies

#1011 Network form updates
  bin/src/app.rs
  crates/networks/src/commands.rs
  crates/networks/src/lib.rs
  gui/package.json
  gui/src/routes/home/_l/settings/_l/networks/_l/$name.edit.tsx
  gui/src/routes/home/_l/settings/_l/networks/_l/new.tsx
  packages/types/network.ts
  yarn.lock
Labels: A-feature, B-bugfix

#1072 Fix dependabot config file
  .github/dependabot.yml
Labels: B-bugfix

#1070 Updating sidebar
  .yarn/releases/yarn-4.0.2.cjs
  .yarnrc.yml
  gui/src/components/AppNavbar.tsx
  gui/src/components/Breadcrumbs.tsx
  gui/src/routes/home/_l.tsx
  package.json
  yarn.lock
Labels: C-chore

#1076 Refactor Networks to SerializedNetworks
  crates/crypto/src/lib.rs
  crates/networks/src/commands.rs
  crates/networks/src/init.rs
  crates/networks/src/lib.rs
Labels: A-refactor

#1071 Add migrations to networks
  Cargo.lock
  Cargo.toml
  crates/networks/Cargo.toml
  crates/networks/src/init.rs
  crates/networks/src/lib.rs
  crates/networks/src/migrations.rs
Labels: A-enhancement

#1079 move tempfile to dev dependencies
  crates/networks/Cargo.toml
Labels: C-chore
