Repository ethui/ethui, pull requests merged in 2025-06, with the labels that each got.

#1284 Update `cc` dependency to fix local Mac build
  Cargo.lock
Labels: C-chore

#1272 Update dependencies to support Etherscan V2 API
  Cargo.lock
  Cargo.toml
  crates/rpc/src/methods/send_transaction.rs
  crates/rpc/src/methods/sign_message.rs
  crates/settings/src/utils.rs
  crates/simulator/src/evm.rs
  crates/sync/alchemy/src/client.rs
  crates/sync/anvil/src/expanders.rs
  crates/sync/anvil/src/tracker.rs
  crates/sync/src/utils.rs
  crates/types/src/network.rs
  crates/wallets/src/signer.rs
  deny.toml
Labels: A-enhancement

#1274 Padding issues
  gui/src/components/Breadcrumbs.tsx
  gui/src/routes/home/_l/contracts/_l/index.tsx
Labels: A-enhancement

#1287 Shows app version on UI
  gui/src/components/AppSidebar.tsx
  gui/src/routeTree.gen.ts
  gui/src/routes/home/_l/settings/_l/about.tsx
Labels: A-feature

#1294 Update to kameo 0.16
  Cargo.lock
  Cargo.toml
  crates/forge/src/actor.rs
Labels: C-dependencies

#1293 Add ABI form package
  .github/workflows/nodejs.yml
  gui/package.json
  gui/src/components/ContractCallForm.tsx
  gui/src/routes/dialog/_l/tx-review.$id.tsx
  package.json
  packages/abiparse/README.md
  packages/abiparse/build.mjs
  packages/abiparse/index.test.ts
  packages/abiparse/index.ts
  packages/abiparse/package.json
  packages/abiparse/src/utils.ts
  packages/abiparse/tsconfig.json
  packages/form/.gitignore
  packages/form/.tool-versions
  packages/form/README.md
  packages/form/package.json
  packages/form/src/AbiInput.tsx
  packages/form/src/AbiItemForm.tsx
  packages/form/src/AbiItemFormWithPreview.tsx
  packages/form/src/ArrayInput.tsx
  packages/form/src/Basic.tsx
  packages/form/src/utils.tsx
  packages/form/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: A-enhancement

#1295 Update to biome 2
  biome.json
  gui/src/components/AddressView.tsx
  gui/src/components/AnimatedOutlet.tsx
  gui/src/components/AppSidebar.tsx
  gui/src/components/BalancesList.tsx
  gui/src/components/Breadcrumbs.tsx
  gui/src/components/CommandBar.tsx
  gui/src/components/ContractCallForm.tsx
  gui/src/components/ERC20View.tsx
  gui/src/components/HashView.tsx
  gui/src/components/QuickAddressSelect.tsx
  gui/src/components/QuickFastModeToggle.tsx
  gui/src/components/QuickNetworkSelect.tsx
  gui/src/components/Settings/Wallet/HDWallet.tsx
  gui/src/components/Settings/Wallet/Impersonator.tsx
  gui/src/components/Settings/Wallet/JsonKeystore.tsx
  gui/src/components/Settings/Wallet/Ledger.tsx
  gui/src/components/Settings/Wallet/Plaintext.tsx
  gui/src/components/Settings/Wallet/PrivateKey.tsx
  gui/src/components/Settings/Wallets.tsx
  gui/src/hooks/useNoticeAlchemyKeyMissing.tsx
  gui/src/hooks/useNoticeNewVersion.tsx
  gui/src/main.tsx
  gui/src/routes/__root.tsx
  gui/src/routes/dialog/_l/chain-add.$id.tsx
  gui/src/routes/dialog/_l/chain-switch.$id.tsx
  gui/src/routes/dialog/_l/erc1155-add.$id.tsx
  gui/src/routes/dialog/_l/erc20-add.$id.tsx
  gui/src/routes/dialog/_l/erc721-add.$id.tsx
  gui/src/routes/dialog/_l/msg-sign.$id.tsx
  gui/src/routes/dialog/_l/tx-review.$id.tsx
  gui/src/routes/dialog/_l/wallet-unlock.$id.tsx
  gui/src/routes/home/_l.tsx
  gui/src/routes/home/_l/connections.tsx
  gui/src/routes/home/_l/contracts/_l/$chainId.$address.tsx
  gui/src/routes/home/_l/contracts/_l/_l.add.tsx
  gui/src/routes/home/_l/contracts/_l/index.tsx
  gui/src/routes/home/_l/onboarding.tsx
  gui/src/routes/home/_l/settings/_l/foundry.tsx
  gui/src/routes/home/_l/settings/_l/general.tsx
  gui/src/routes/home/_l/settings/_l/networks/_l/index.tsx
  gui/src/routes/home/_l/settings/_l/networks/_l/new.tsx
  gui/src/routes/home/_l/settings/_l/tokens.tsx
  gui/src/routes/home/_l/transactions.tsx
  gui/src/routes/home/_l/transfer/_l.erc20.tsx
  gui/src/routes/home/_l/transfer/_l.eth.tsx
  gui/src/store/useBalances.ts
  gui/src/store/useBlacklist.ts
  gui/src/store/useContracts.ts
  gui/src/store/useNetworks.ts
  gui/src/store/useSettings.ts
  gui/src/store/useTheme.ts
  gui/src/store/useWallets.ts
  gui/vite.config.ts
  icons/generate.tsx
  package.json
  packages/abiparse/index.ts
  packages/form/src/ArrayInput.tsx
  packages/form/src/Basic.tsx
  yarn.lock
Labels: C-dependencies

#1300 Prototype: ethui_get_contract_abi RPC endpoint
  Cargo.lock
  crates/rpc/Cargo.toml
  crates/rpc/src/error.rs
  crates/rpc/src/lib.rs
  crates/rpc/src/methods/ethui/abi_for_contract.rs
  crates/rpc/src/methods/ethui/mod.rs
  crates/rpc/src/methods/mod.rs
Labels: A-feature
