Repository ethui/ethui, pull requests merged in 2025-03, with the labels that each got.

#1100 Fixing cargo-deny workflows
  .github/workflows/rust.yml
Labels: C-chore

#1101 Add migrations to connections
  Cargo.lock
  crates/connections/Cargo.toml
  crates/connections/src/init.rs
  crates/connections/src/lib.rs
  crates/connections/src/migrations.rs
  crates/connections/src/store.rs
Labels: A-refactor

#1103 Update new release download url
  gui/src/hooks/useNoticeNewVersion.tsx
Labels: A-refactor

#1046 Add internal_id field to Networks
  crates/networks/src/commands.rs
  crates/networks/src/lib.rs
  crates/networks/src/migrations.rs
  crates/rpc/src/lib.rs
  crates/rpc/src/methods/chain_add.rs
  crates/rpc/src/methods/chain_update.rs
  crates/types/src/dedup_chain_id.rs
  crates/types/src/lib.rs
  crates/types/src/network.rs
  crates/types/src/new_network_params.rs
Labels: A-enhancement

#1102 Add dedup_id migration to affinities
  crates/connections/src/commands.rs
  crates/connections/src/ctx.rs
  crates/connections/src/migrations.rs
  crates/connections/src/store.rs
  crates/rpc/src/lib.rs
  crates/rpc/src/methods/chain_add.rs
  crates/types/src/affinity.rs
  gui/src/routes/home/_l/connections.tsx
  packages/types/index.ts
Labels: A-refactor

#1109 Fixing cargo-deny alerts
  Cargo.lock
  deny.toml
Labels: C-dependencies

#1107 Settings migrations
  Cargo.lock
  crates/settings/Cargo.toml
  crates/settings/src/init.rs
  crates/settings/src/lib.rs
  crates/settings/src/migrations.rs
Labels: C-chore

#1104 Replacing `chain_id` as the network identifier with `internal_id`
  crates/broadcast/src/lib.rs
  crates/connections/src/commands.rs
  crates/connections/src/ctx.rs
  crates/connections/src/init.rs
  crates/connections/src/store.rs
  crates/networks/src/init.rs
  crates/networks/src/lib.rs
  crates/rpc/src/methods/chain_update.rs
  crates/types/src/affinity.rs
  crates/types/src/lib.rs
  crates/types/src/network.rs
  crates/ws/src/init.rs
  crates/ws/src/peers.rs
Labels: A-refactor

#1108 Refactor DedupChainId into a struct
  crates/broadcast/src/lib.rs
  crates/connections/src/commands.rs
  crates/connections/src/ctx.rs
  crates/connections/src/migrations.rs
  crates/networks/src/migrations.rs
  crates/types/src/dedup_chain_id.rs
  crates/types/src/network.rs
  crates/ws/src/peers.rs
  packages/types/network.ts
Labels: A-refactor

#1111 Network migration to use DedupChainId
  crates/connections/src/commands.rs
  crates/connections/src/ctx.rs
  crates/connections/src/init.rs
  crates/db/src/init.rs
  crates/networks/src/init.rs
  crates/networks/src/lib.rs
  crates/networks/src/migrations.rs
  crates/rpc/src/lib.rs
  crates/rpc/src/methods/chain_add.rs
  crates/rpc/src/methods/chain_update.rs
  crates/rpc/src/methods/send_transaction.rs
  crates/rpc/src/methods/sign_message.rs
  crates/rpc/src/methods/token_add.rs
  crates/sync/anvil/src/init.rs
  crates/sync/src/lib.rs
  crates/types/src/network.rs
  crates/types/src/new_network_params.rs
  gui/src/components/AddressView.tsx
  gui/src/components/BalancesList.tsx
  gui/src/components/ERC20View.tsx
  gui/src/components/QuickNetworkSelect.tsx
  gui/src/hooks/useNoticeAlchemyKeyMissing.tsx
  gui/src/routes/dialog/_l/chain-add.$id.tsx
  gui/src/routes/dialog/_l/chain-switch.$id.tsx
  gui/src/routes/dialog/_l/erc20-add.$id.tsx
  gui/src/routes/dialog/_l/tx-review.$id.tsx
  gui/src/routes/home/_l/connections.tsx
  gui/src/routes/home/_l/contracts/_l/index.tsx
  gui/src/routes/home/_l/settings/_l/networks/_l/$name.edit.tsx
  gui/src/routes/home/_l/settings/_l/networks/_l/index.tsx
  gui/src/routes/home/_l/settings/_l/networks/_l/new.tsx
  gui/src/routes/home/_l/settings/_l/tokens.tsx
  gui/src/routes/home/_l/transactions.tsx
  gui/src/store/useBalances.ts
  gui/src/store/useBlacklist.ts
  gui/src/store/useContracts.ts
  gui/src/store/useNetworks.tsx
  packages/types/network.ts
Labels: A-refactor

#1124 Update to alloy 0.12
  Cargo.lock
  Cargo.toml
  crates/networks/src/lib.rs
  crates/rpc/src/methods/send_call.rs
  crates/sync/anvil/src/tracker.rs
  crates/sync/anvil/src/utils.rs
  crates/sync/src/utils.rs
  crates/types/src/network.rs
Labels: dependencies

#1125 Update foundry
  Cargo.lock
  Cargo.toml
  deny.toml
Labels: dependencies

#1112 New onboarding flow
  bin/src/app.rs
  bin/src/windows/main.rs
  crates/broadcast/src/lib.rs
  crates/settings/src/commands.rs
  crates/settings/src/init.rs
  crates/settings/src/lib.rs
  crates/settings/src/migrations.rs
  crates/settings/src/onboarding.rs
  crates/wallets/src/lib.rs
  crates/ws/src/peers.rs
  gui/package.json
  gui/src/components/AnimatedOutlet.tsx
  gui/src/components/AppSidebar.tsx
  gui/src/components/Logo.tsx
  gui/src/routeTree.gen.ts
  gui/src/routes/home/_l/onboarding.tsx
  gui/src/routes/home/_l/settings/_l/general.tsx
  gui/src/routes/onboarding/_l.tsx
  gui/src/routes/onboarding/_l/alchemy.tsx
  gui/src/routes/onboarding/_l/extension.tsx
  gui/src/routes/onboarding/_l/index.tsx
  gui/src/routes/onboarding/_l/thank-you.tsx
  gui/src/routes/onboarding/_l/wallets/_l.tsx
  gui/src/routes/onboarding/_l/wallets/_l/$name.edit.tsx
  gui/src/routes/onboarding/_l/wallets/_l/index.tsx
  gui/src/routes/onboarding/_l/wallets/_l/new.tsx
  packages/types/settings.ts
  yarn.lock
Labels: A-feature

#1131 Fixes an alloy or anvil issue with block subscriptions
  crates/sync/anvil/src/tracker.rs
Labels: B-bugfix

#1130 Improved Forge Sync
  Cargo.lock
  Cargo.toml
  bacon.toml
  bin/Cargo.toml
  crates/broadcast/src/lib.rs
  crates/forge/Cargo.toml
  crates/forge/src/abi.rs
  crates/forge/src/actor.rs
  crates/forge/src/error.rs
  crates/forge/src/init.rs
  crates/forge/src/lib.rs
  crates/forge/src/manager.rs
  crates/forge/src/utils.rs
  crates/forge/src/watcher.rs
  packages/data/gen/tokens.json
Labels: A-refactor

#1134 Boxes a large enum variant
  crates/forge/src/actor.rs
  crates/rpc/src/methods/sign_message.rs
  crates/types/src/events.rs
Labels: C-chore

#1132 Moving to rust nightly
  .cargo/config.toml
  .github/workflows/release.yml
  .github/workflows/rust.yml
  .mise.toml
  Cargo.toml
  crates/forge/src/actor.rs
  crates/rpc/src/methods/sign_message.rs
  crates/types/src/events.rs
  rust-toolchain.toml
Labels: C-chore

#1149 Basic ETH/ERC20 transfers
  gui/package.json
  gui/src/components/ContractCallForm.tsx
  gui/src/components/ERC20View.tsx
  gui/src/components/TransferForm.tsx
  gui/src/routeTree.gen.ts
  gui/src/routes/home/_l/transfer/-common.tsx
  gui/src/routes/home/_l/transfer/_l.erc20.tsx
  gui/src/routes/home/_l/transfer/_l.eth.tsx
  gui/src/routes/home/_l/transfer/_l.tsx
  yarn.lock
Labels: A-feature

#1150 Tweaking transactions page animations
  gui/src/routes/home/_l/transactions.tsx
Labels: A-enhancement

#1151 better output for transaction calls
  gui/package.json
  gui/src/components/ContractCallForm.tsx
  gui/src/components/HashView.tsx
  gui/src/routes/home/_l/transactions.tsx
  gui/src/routes/home/_l/transfer/_l.erc20.tsx
  gui/src/routes/home/_l/transfer/_l.eth.tsx
  packages/types/index.ts
  yarn.lock
Labels: A-enhancement

#1152 Several fixes and improvements to the command bar
  crates/settings/src/commands.rs
  crates/settings/src/lib.rs
  gui/src/components/CommandBar.tsx
  gui/src/store/useNetworks.ts
  gui/src/store/useSettings.ts
  gui/src/store/useTheme.ts
  gui/src/store/useWallets.ts
Labels: A-enhancement

#1155 Fixing abi form layout
  gui/src/main.css
  packages/form/src/AbiItemFormWithPreview.tsx
Labels: B-bugfix

#1157 Fixing incorrectly displayed erc20 transfer
  gui/src/routes/dialog/_l/tx-review.$id.tsx
Labels: B-bugfix

#1153 Fix add contract network
  bin/src/app.rs
  bin/src/commands.rs
  crates/networks/src/commands.rs
Labels: B-bugfix

#1158 Fixing kameo warnings
  crates/forge/src/actor.rs
Labels: C-chore

#1159 slightly faster transition anims
  gui/src/components/AnimatedOutlet.tsx
Labels: A-enhancement

#1154 Update anvil sync and db queries to receive DedupChainId
  .sqlx/query-46f91960e81a5f3fab56c738c64fb5ce3a11a7d6bbdd90ac511a641cb370dcc7.json
  bin/src/app.rs
  crates/db/src/lib.rs
  crates/db/src/queries/events.rs
  crates/sync/anvil/src/expanders.rs
  crates/sync/anvil/src/init.rs
  crates/sync/anvil/src/tracker.rs
  crates/types/src/dedup_chain_id.rs
  crates/types/src/events.rs
  crates/types/src/ui_events.rs
  migrations/25_delete_erc721_and_erc1155.sql
Labels: A-refactor

#1172 Dependabot config tweaks
  .github/dependabot.yml
Labels: C-chore

#1162 Json view for message signatures
  bin/capabilities/main.json
  crates/dialogs/src/presets.rs
  crates/rpc/src/methods/sign_message.rs
  gui/package.json
  gui/src/components/AnimatedOutlet.tsx
  gui/src/components/JsonView.tsx
  gui/src/main.css
  gui/src/routes/dialog/_l.tsx
  gui/src/routes/dialog/_l/msg-sign.$id.tsx
  yarn.lock
Labels: A-enhancement

#1180 Fix incorrect parsing of ERC20 logs
  gui/src/routes/dialog/_l/tx-review.$id.tsx
Labels: B-bugfix
