Repository ethui/ethui, pull requests merged in 2025-07, with the labels that each got.

#1317 node 24
  .github/workflows/nodejs.yml
  .github/workflows/release.yml
  .mise.toml
  .tool-versions
  .yarn/releases/yarn-4.6.0.cjs
  .yarn/releases/yarn-4.9.2.cjs
  .yarnrc.yml
  biome.json
  package.json
Labels: C-chore

#1318 remove unused deps
  Cargo.lock
  crates/broadcast/Cargo.toml
  crates/crypto/Cargo.toml
  crates/simulator/Cargo.toml
  crates/sync/anvil/Cargo.toml
  gui/package.json
  yarn.lock
Labels: C-chore

#1319 Fix dependabot security alert 94
  .github/workflows/nodejs.yml
  gui/src/routeTree.gen.ts
  package.json
  yarn.lock
Labels: C-dependencies

#1324 Fix transaction format type
  gui/src/routes/home/_l/transactions.tsx
Labels: B-bugfix

#1326 setup prelude module
  Cargo.lock
  crates/broadcast/src/lib.rs
  crates/connections/src/commands.rs
  crates/connections/src/permissions.rs
  crates/db/src/commands.rs
  crates/db/src/queries/chain_tip.rs
  crates/db/src/queries/contracts.rs
  crates/db/src/queries/erc20.rs
  crates/db/src/queries/transactions.rs
  crates/db/src/utils.rs
  crates/dialogs/src/global.rs
  crates/dialogs/src/handle.rs
  crates/exchange-rates/src/init.rs
  crates/forge/src/abi.rs
  crates/forge/src/actor.rs
  crates/networks/src/commands.rs
  crates/networks/src/lib.rs
  crates/rpc/src/commands.rs
  crates/rpc/src/error.rs
  crates/rpc/src/lib.rs
  crates/rpc/src/methods/send_call.rs
  crates/rpc/src/methods/send_transaction.rs
  crates/rpc/src/methods/token_add.rs
  crates/settings/src/actor.rs
  crates/settings/src/lib.rs
  crates/simulator/src/types.rs
  crates/simulator/tests/detris.rs
  crates/sync/alchemy/src/lib.rs
  crates/sync/alchemy/src/types.rs
  crates/sync/src/lib.rs
  crates/sync/src/worker.rs
  crates/types/Cargo.toml
  crates/types/src/affinity.rs
  crates/types/src/contracts.rs
  crates/types/src/events.rs
  crates/types/src/lib.rs
  crates/types/src/network.rs
  crates/types/src/prelude.rs
  crates/wallets/src/utils.rs
  crates/wallets/src/wallet.rs
  crates/wallets/src/wallets/impersonator.rs
  crates/wallets/src/wallets/ledger.rs
  crates/wallets/src/wallets/private_key.rs
  crates/ws/src/peers.rs
Labels: A-refactor

#1329 Less indirection on checking onboarding steps on the backend
  Cargo.lock
  crates/broadcast/src/lib.rs
  crates/dialogs/src/handle.rs
  crates/forge/src/actor.rs
  crates/settings/Cargo.toml
  crates/settings/src/actor.rs
  crates/settings/src/init.rs
  crates/sync/alchemy/src/lib.rs
  crates/sync/anvil/src/tracker.rs
Labels: A-refactor

#1330 silence UI error when anvil is offline
  gui/src/store/useBalances.ts
Labels: B-bugfix

#1332 Add exponencial backoff when checking for new blocks
  crates/sync/anvil/src/tracker.rs
Labels: A-refactor

#1335 ethui-crypto: replace unwrap() calls with proper error handling
  crates/crypto/src/lib.rs
Labels: A-refactor

#1337 Fixing error on BigInt parsing
  gui/package.json
  package.json
  yarn.lock
Labels: B-bugfix

#1334 Remove mise-en-place
  .mise.toml
  .mise/helpers/bash_ansi_color.sh
  .mise/tasks/ext/source
  .mise/tasks/sqlx
  .mise/tasks/update-version
  .rgignore
  CONTRIBUTING.md
  bin/Cargo.toml
  bin/src/app.rs
  crates/args/src/lib.rs
  package.json
  scripts/icons
  scripts/launch
  scripts/setup
Labels: C-chore

#1320 Forge test cli subcommand
  Cargo.lock
  Cargo.toml
  bin/Cargo.toml
  bin/src/app.rs
  bin/src/lib.rs
  crates/args/Cargo.toml
  crates/args/src/lib.rs
  crates/forge-traces/Cargo.toml
  crates/forge-traces/src/lib.rs
  crates/rpc/Cargo.toml
  crates/rpc/src/lib.rs
  crates/rpc/src/methods/ethui/forge_test_traces.rs
  crates/rpc/src/methods/ethui/mod.rs
  crates/ws/src/server.rs
Labels: A-enhancement

#1339 moving from yarn to pnpm
  .github/workflows/nodejs.yml
  .github/workflows/release.yml
  .yarn/releases/yarn-4.9.2.cjs
  .yarnrc.yml
  CONTRIBUTING.md
  bin/tauri.conf.json
  bin/tauri.dev.conf.json
  gui/package.json
  package.json
  packages/data/index.ts
  packages/types/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/launch
  scripts/postbuild.sh
  scripts/setup
  yarn.lock
Labels: C-chore

#1342 refactor nix flake
  flake.nix
  nix/devshell.nix
  nix/package.nix
Labels: A-refactor

#1351 fix block number and timestamp on revm simulations
  crates/simulator/src/lib.rs
Labels: B-bugfix

#1354 onboarding page less visually heavy
  gui/src/components/AppSidebar.tsx
  gui/src/routes/home/_l/onboarding.tsx
Labels: A-enhancement

#1355 turn fast mode toggle into a Switch again
  gui/src/components/QuickFastModeToggle.tsx
  gui/src/main.css
Labels: B-bugfix

#1348 Auto submit general settings
  bin/src/app.rs
  crates/settings/src/actor.rs
  crates/settings/src/commands.rs
  crates/settings/src/utils.rs
  crates/tracing/src/lib.rs
  gui/package.json
  gui/src/routes/home/_l/settings/_l/general.tsx
  pnpm-lock.yaml
Labels: A-enhancement

#1360 mprocs.yaml for easy startup app + ui + demo + explorer
  mprocs.yaml
Labels: C-chore

#1361 using walkdir instead of glob to find foundry roots
  Cargo.lock
  Cargo.toml
  crates/forge/Cargo.toml
  crates/forge/src/actor.rs
Labels: A-enhancement

#1363 settings > start_minimized no longer accidentally ignored
  bin/src/app.rs
Labels: B-bugfix

#1364 Fix fast mode initial rendering
  gui/src/components/QuickFastModeToggle.tsx
Labels: B-bugfix

#1358 New wallet/network switching interface
  gui/package.json
  gui/src/components/AddressView.tsx
  gui/src/components/AppNavbar.tsx
  gui/src/components/AppSidebar.tsx
  gui/src/components/QuickAddressSelect.tsx
  gui/src/components/QuickNetworkSelect.tsx
  gui/src/components/QuickWalletSelect.tsx
  gui/src/components/SearchInput.tsx
  gui/src/components/Topbar.tsx
  gui/src/components/WalletSidebar/NetworkSelector.tsx
  gui/src/components/WalletSidebar/WalletSelector.tsx
  gui/src/components/WalletSidebar/index.tsx
  gui/src/components/WalletSidebar/useSidebarSearch.ts
  gui/src/routes/home/_l.tsx
  gui/src/store/useWallets.ts
  pnpm-lock.yaml
Labels: A-enhancement

#1367 Fix background color on address hover
  gui/src/components/AddressView.tsx
Labels: B-bugfix

#1373 Setting up tauri updater manifest
  .github/workflows/release.yml
  bin/tauri.conf.json
Labels: A-enhancement

#1378 Improves window title for main and dialog windows
  bin/src/windows/mod.rs
  bin/tauri.dev.conf.json
  gui/index.html
Labels: A-enhancement

#1379 Fixes infinite scroll bug
  gui/src/routes/home/_l/transactions.tsx
Labels: B-bugfix

#1380 Enabling auto updates for macos
  .github/workflows/rust.yml
  Cargo.lock
  bin/Cargo.toml
  bin/capabilities/main.json
  bin/src/app.rs
  bin/src/lib.rs
  bin/src/updater.rs
  crates/types/src/ui_events.rs
  gui/package.json
  gui/src/components/CommandBar.tsx
  gui/src/hooks/useEventListener.ts
  gui/src/hooks/useNoticeNewVersion.tsx
  gui/src/hooks/useUpdates.tsx
  gui/src/routes/dialog/_l/msg-sign.$id.tsx
  gui/src/routes/home/_l.tsx
  gui/src/routes/home/_l/account.tsx
  gui/src/routes/home/_l/connections.tsx
  gui/src/routes/home/_l/transactions.tsx
  pnpm-lock.yaml
Labels: A-feature

#1381 Add Claude Code GitHub Workflow
  .github/workflows/claude-code-review.yml
  .github/workflows/claude.yml
Labels: C-chore
