Repository ethui/ethui, pull requests merged in 2025-04, with the labels that each got.

#1191 Bump react version to match react-dom
  gui/package.json
  yarn.lock
Labels: C-dependencies

#1209 Fix AbiItemForm when there are no inputs
  packages/form/src/AbiItemFormWithPreview.tsx
Labels: B-bugfix

#1211 Fixing abi forms due to dependency issues
  gui/package.json
  packages/form/package.json
  yarn.lock
Labels: B-bugfix

#1224 Fix newly deployed contract ABI not recognised
  .sqlx/query-142018530d9f46786a8733e8b9261f7931f6ea5519ad83eb56772631ebcd0800.json
  .sqlx/query-7fabd2f7afc4576b726a6dbb11413e3ebf0adc0130d10aa98fabfa56d9e41607.json
  crates/db/src/lib.rs
  crates/sync/anvil/src/tracker.rs
Labels: B-bugfix

#1222 Bundle libusb into MacOS app bundle
  assets/libusb-1.0.dylib
  bin/tauri.conf.json
  package.json
  scripts/postbuild.sh
Labels: A-feature

#1223 Fix bug with Connections not updating to the selected network
  gui/src/routes/home/_l/connections.tsx
  packages/types/index.ts
Labels: B-bugfix

#1232 Fix clippy uninlined format warnings
  crates/connections/src/migrations.rs
  crates/db/src/queries/chain_tip.rs
  crates/db/src/queries/contracts.rs
  crates/db/src/queries/erc1155.rs
  crates/db/src/queries/erc721.rs
  crates/db/src/queries/native_balance.rs
  crates/db/src/queries/transactions.rs
  crates/ws/src/server.rs
Labels: C-chore
